homebrewclient-test: homebrewclient-test.cpp ../../lib/freedmrlib.a
	g++ -Wall -lpthread -lcrypto -lssl -o homebrewclient-test homebrewclient-test.cpp ../../lib/freedmrlib.a

clean:
	rm -f *.o *~ homebrewclient-test
